server:
  address: localhost
  port: 8080



#  error:
#    include-exception: true
#    include-message: on_param
#    include-binding-errors: on_param
#    include-stacktrace: on_param

spring:
  messages:
    basename: messages,config.i18n.messages
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
        open_in_view: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.apache.coyote.http11: debug

service:
  active: dev





file:
  dir: /Users/george/dev/images/
